version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres
    container_name: kpu_db
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=kpu_db
      - POSTGRES_USER=kpu
      - POSTGRES_PASSWORD=kpu1234

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    container_name: kpu_web
    volumes:
      - ./:/app/
    command: ["./manage.py", "runserver", "0:8000"]
    environment:
     - DJANGO_DB_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - 5000:8000
